### ISSUE TITLE
syncfiles command copies wrong file

### ISSUE THREAD

**Issue by thijstriemstra** [django-cumulus/django-cumulus#184]
Let's say your static root contains the following directory structure:
```
css/style.css
admin/css/style.css
```
There's a bug in the abspath/relpath logic that uploads the second file twice because it checks using `endswith`. PR follows.

**Comment by rizumu** [comment]
@thijstriemstra Thanks for reporting this, we can get a PR merged in quickly for a fix.

**Comment by thijstriemstra** [comment]
Thanks for the quick reply. I hope this PR fixes it correctly for both static and media content, I only use and tested it for static.

**Comment by thijstriemstra** [comment]
Any eta for a new release?

**Comment by ferrix** [comment]
10 minutes.

**Comment by thijstriemstra** [comment]
Thanks!
