### ISSUE TITLE
django-cumulus uploads corrupted images files

### ISSUE THREAD

**Issue by crucialfelix** [django-cumulus/django-cumulus#192]
I recently updated from 1.0.8 to 1.0.19

First of all, for semver you should have changed the release number. 1.1 or even 2.0 because you introduced breaking changes. These were not patch releases.

I have no idea why image uploads are corrupted now. It appears to upload okay, it sets the content type, but the images are unreadable.

```python
---> 38     return storage.save(filename, file)
     39

ipdb> storage
<cumulus.storage.SwiftclientStorage object at 0x1080856d0>
ipdb> file
<InMemoryUploadedFile: 474117-574384-tmpx45Mzt.jpg (image/jpeg)>
ipdb>
```

http://2f72cea349946a314d10-a6b96514f90d938bd50c41212fd3a66a.r78.cf2.rackcdn.com/245202-505674-unnamed%20(3).jpg

**Comment by ferrix** [comment]
I cannot reproduce.
