### ISSUE TITLE
Maintain the changelog up to date (from now on)

### ISSUE THREAD

**Issue by rasca** [django-cumulus/django-cumulus#193]
I've recently migrated a project from django 1.4 LTS to 1.7, and in the process I upgraded django-cumulus to 1.0.19

I had several problems while upgrading, mainly from the lack of a changelog. I propose modifying the pull requests process, requiring an entry in the changelog (if applicable).

If you don't want this for whatever reason, I volunteer to write the changelog before releasing a new version.

Thanks!

**Comment by ferrix** [comment]
That's actually something we discussed with @rizumu. I have been keeping a release changelog in the annotated tags myself. It is very much on the topical level which may not be enough for backward compatibility. So we very much feel you.
