### ISSUE TITLE
Module "cumulus.storage" does not define a "CumulusStorage" attribute/class

### ISSUE THREAD

**Issue by DannyAziz** [django-cumulus/django-cumulus#200]
I've set DEFAULT_FILE_STORAGE = 'cumulus.storage.CumulusStorage' in the settings and I've also tried the models.py way but neither work.

Any help?

**Comment by erg0dic** [comment]
You have to use the development build right now:
```pip install git+git://github.com/django-cumulus/django-cumulus.git@master```

Note that I was unable to install the package with ```pip install django-cumulus==dev```, as suggested in the docs.

**Comment by jrthorne** [comment]
This is still an issue. Still need to use the development build.

**Comment by ferrix** [comment]
This has been fixed in 1.0.21
